server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: listing-service
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/v1/listings/**
        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**
eureka:
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'