version: '3.8'
name: "real-estate-infra"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: real-estate-db
    ports:
      - '5432:5432'
  mongodb:
    image: mongo
    environment:
      MONGODB_DB: 'payment-db'
    ports:
      - '27017:27017'
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '5672:5672'
      - '15672:15672'